from building import *
import os
import rtconfig


cwd = GetCurrentDir()

# add general drivers
src = []
path =  [cwd]

# if GetDepend(['BSP_USING_AUDIO_RECORD']):
    # src += Glob('drv_mic.c')

if GetDepend(['BSP_USING_AUDIO_PLAY']):
    # src += Glob('drv_sound.c')
    src += Glob('drv_es8388.c')

group = DefineGroup('audio-codec', src, depend = ['BSP_USING_AUDIO'], CPPPATH = path)

Return('group')
