import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = []
path =  [cwd]

if GetDepend(['BSP_USING_HYPERAM']):
    src += Glob('drv_hyperam.c')

if GetDepend(['BSP_USING_AUDIO']):
    src += Glob('audio/drv_es8388.c')
    path += [cwd + '/audio']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
